#!/usr/bin/php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Plum\Commands\Kernel;

$kernel = new Kernel();

$kernel->run(
  new Symfony\Component\Console\Input\ArgvInput,
  new Symfony\Component\Console\Output\ConsoleOutput
);
